name: viziag_mart
description: "Viziag Mart - Hyperlocal Marketplace with Admin Approval & Dual Dashboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.2.0
  url_launcher: ^6.2.6

  # 📍 जियोफेंसिंग और लाइव जीपीएस ट्रैकिंग के लिए नए पैकेजेस:
  geolocator: ^11.0.0           # ड्राइवर की रियल-टाइम GPS लोकेशन (Lat/Lng) निकालने के लिए
  geofencing_api: ^1.0.8        # एरिया बाउंड्री और फेंसिंग सेट करने के लिए
  google_maps_flutter: ^2.5.3   # मैप्स पर लाइव टेम्पो की लोकेशन दिखाने के लिए

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
