name: desi_ai_app
description: "A new Flutter project for AI Agent & Studio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # जरूरी पैकेजेस
  shared_preferences: ^2.2.3
  http: ^1.2.0
  
  # अगर तुझे इनकी भी जरूरत नहीं है, तो इन्हें भी हटा सकता है
  supabase_flutter: ^2.5.4
  image_picker: ^1.0.7
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
